BEGIN;
DROP INDEX IF EXISTS idx_preservation_details_gin;
DROP INDEX IF EXISTS idx_preservation_content_time;
DROP INDEX IF EXISTS idx_privacy_tenant;
DROP INDEX IF EXISTS idx_privacy_content;
DROP TABLE IF EXISTS retention_rules;
DROP TABLE IF EXISTS preservation_events;
DROP TABLE IF EXISTS privacy_records;
ALTER TABLE audit_events DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE rights_records DROP COLUMN IF EXISTS tenant_id;
ALTER TABLE content_items DROP COLUMN IF EXISTS tenant_id;
DROP TABLE IF EXISTS tenants;
COMMIT;
